### ISSUE TITLE
INSTALLATION

### ISSUE THREAD

**Issue by amo74** [corvis/prana_rc#28]
Hi.

I have Raspberry PI 3 with the latest SO.
With

pip install prana-rc 

i have an error, "no such file or directory"

**Comment by corvis** [comment]
The error indicates you don't have pip installed. Pip us a python package manager. Try to install pip with `sudo apt install python3-pip` and then follow the guide.

**Comment by amo74** [comment]
I have pip just installed but does not work.

**Comment by amo74** [comment]
Pip just installed but does not work

**Comment by amo74** [comment]
pi@raspberrypi:~ $ pip install prana-rc[server-tornado]
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting prana-rc[server-tornado]
  Using cached https://files.pythonhosted.org/packages/cb/40/1f16a3ea95e7c63e62008f6cd676976c81313c97f472e3b5ef0311545be4/prana_rc-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-stpsWV/prana-rc/setup.py", line 61, in <module>
        with open(readme_file) as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip-install-stpsWV/prana-rc/../media/pypi-description.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-stpsWV/prana-rc/
pi@raspberrypi:~ $

**Comment by amo74** [comment]
Ok. Work with pip3
